### ISSUE TITLE
Using prerender_location in Javascript

### ISSUE THREAD

**Issue by yhkang95** [mariopeixoto/react-router-rails#13]
I'm using react-router-rails with fluxxor. Since I need to pass in the flux instance, I cannot do a server-side rendering with your view helper. But I run into trouble when I use the back button if I don't use prerender_location. Is there a way I can incorporate prerender_location into ReactRouter.run?

**Comment by mariopeixoto** [comment]
In theory, you would not need the prerender_location while rendering on the client because the prerender_location just represents the current url.

Could you provide some example or information on what the problem is or how to reproduce?

**Comment by yhkang95** [comment]
### routes.rb

``` ruby
Rails.application.routes.draw do
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations'}

  root 'application#index'

  get 'enrolled' => 'pages#enrolled'
  get 'current_user' => 'users#get_current_user'
  get 'categories' => 'categories#index'
  get 'courses/:id' => 'courses#show'
  resources :courses, only: [:create, :update] do
    resources :lectures, only: [:create]
  end

  get '/*path' => 'application#index'
end
```

### Router.js.jsx

``` javascript
// routes
var routes = (
  <Route handler={App}>
    <Route handler={SignInForm} path='/signin' />
    <Route handler={SignUpForm} path='/signup' />
    <Route handler={EnrolledCourses} path='/my_courses' />
    <Route handler={ProfileForm} path='/profile' />
    <Route handler={ShowCourse} path='/course/:id' />
    <Route handler={EditCourseForm} path='/course/:id/edit' />
  </Route>
);

// router
module.exports = ReactRouter.create({
  routes: routes,
  location: ReactRouter.HistoryLocation
});
```

### application.js

``` javascript
var router = require('components/Router');

router.run(
  function (Handler) {
    React.render(<Handler flux={flux} />, document.getElementById('content'));
  }
);
```

I'm having a few problems, and I'm suspecting they are both caused by the whole HistoryLocation, HashLocation, etc. deal.

When I navigate around the app, everything runs smoothly, without any pound sign (#) in the url. But when I click the back button, I immediately get a pound sign in the url. 

Then, if I click the back button once more, I can no longer click anything. Even if I just click an empty space, I get this error:

`Error: Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`: .0.2.0`

Then, if I click the back button once more, I get these warnings:

`Warning: Failed Context Types: Required context `router` was not specified in `Link`. Check the render method of `exports`.`

```
Warning: owner-based and parent-based contexts differ (values: `undefined` vs `function (props, context) {
      // This constructor is overridden by mocks. The argument is used
      // by mocks to assert on what gets mounted.

      if ("production" !== "development") {
        ("production" !== "development" ? warning(
          this instanceof Constructor,
          'Something is calling a React component directly. Use a factory or ' +
          'JSX instead. See: https://fb.me/react-legacyfactory'
        ) : null);
      }

      // Wire up auto-binding
      if (this.__reactAutoBindMap) {
        bindAutoBindMethods(this);
      }

      this.props = props;
      this.context = context;
      this.state = null;

      // ReactClasses doesn't have constructors. Instead, they use the
      // getInitialState and componentWillMount methods for initialization.

      var initialState = this.getInitialState ? this.getInitialState() : null;
      if ("production" !== "development") {
        // We allow auto-mocks to proceed as if they're returning null.
        if (typeof initialState === 'undefined' &&
            this.getInitialState._isMockFunction) {
          // This is probably bad practice. Consider warning here and
          // deprecating this convenience.
          initialState = null;
        }
      }
      ("production" !== "development" ? invariant(
        typeof initialState === 'object' && !Array.isArray(initialState),
        '%s.getInitialState(): must return an object or null',
        Constructor.displayName || 'ReactCompositeComponent'
      ) : invariant(typeof initialState === 'object' && !Array.isArray(initialState)));

      this.state = initialState;
    }`) for key (router) while mounting Link (see: http://fb.me/react-context-by-parent)
```

and this error:

`TypeError: undefined is not an object (evaluating 'this.context.router.makeHref')`

I've been trying to fix this for the past few days, and I cannot tell if I'm not using react-router-rails incorrectly or something else incorrectly. Please let me know if you're familiar with the issue.

Thank you!

**Comment by mariopeixoto** [comment]
You are not using the react_router view helper, right?

**Comment by yhkang95** [comment]
I have to use my flux instance, so I have to do a client side rendering.

**Comment by mariopeixoto** [comment]
Are you using the turbolinks gem?

You are not using the view helper, but directly using the react-router javascript library. Then that is probably not a react-router-rails issue.
I'll try to create a small project to reproduce this problem - better if you could provide it. Can you post your Gemfile here?

**Comment by yhkang95** [comment]
### Gemfile

``` ruby
source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'rails-observers'

# authentication
gem 'devise'

# front-end
gem 'bootstrap-sass'
gem 'react-rails'
gem 'bower-rails', '~> 0.9.2'
gem 'browserify-rails'
gem 'react-router-rails', '~>0.13.3'

# file upload
gem 'carrierwave'
gem 'rmagick'

group :development do
  gem 'annotate'
end

group :development, :production do
  gem 'pry-rails'
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
```

### application.js

``` javascript
// This is a manifest file that'll be compiled into application.js, which will include all the files
// listed below.
//
// Any JavaScript/Coffee file within this directory, lib/assets/javascripts, vendor/assets/javascripts,
// or any plugin's vendor/assets/javascripts directory can be referenced here using a relative path.
//
// It's not advisable to add code directly here, but if you do, it'll appear at the bottom of the
// compiled file.
//
// Read Sprockets README (https://github.com/rails/sprockets#sprockets-directives) for details
// about supported directives.
//
//= require jquery
//= require jquery_ujs
//= require turbolinks
//= require react
//= require react_ujs
//= require react-bootstrap
//= require react_router
//= require fluidvids-react
//= require fluxxor
//= require components
//= require_tree .

var router = require('components/Router');

router.run(
  function (Handler) {
    React.render(<Handler flux={flux} />, document.getElementById('content'));
  }
);
```

I don't think I'm directly using the react-router javascript library. I'm using the react-router-rails gem (if that's what you meant?). 

Thank you so much for the help. I'll keep working on it as well.

**Comment by mariopeixoto** [comment]
I know you are using the react-router-rails gem but the gem acts as a bridge between the react-router and rails sprockets. If you don't use the view helper or require the react_router_ujs, you are not touching the gem code at all, you'll only have the react-router.js included on your asset pipeline.

It seems like you are using the turbolinks gem. Can you try remove it? It might be messing up with the browser's requests. You can remove it from the gemfile or remove data-turbolinks attributes from your ERB.

Let me know

**Comment by yhkang95** [comment]
Wow, I think it's working. Thank you so much! Just a quick question: why do I get the pound sign when I click the back button? Also, are there any issues I might run into by removing the turbolinks gem?

**Comment by mariopeixoto** [comment]
Turbolinks is just an optimization for classic applications where for every request a full page (html + assets) is downloaded on the client. 

It's useless for single page applications.

**Comment by yhkang95** [comment]
I almost gave up on transitioning to using single page applications because of this issue. Thank you again for the help!

**Comment by justin808** [comment]
@mariopeixoto is it feasible to use turbolinks with react-router for just a few pages of a larger rails app. https://github.com/shakacode/react_on_rails/ supports react components, and supposed I'd like a given rails path of /spa-1 to point to a rails view where I render a react component that uses react router, and then I'd like to have /spa-2 to go to another view using a different react component also using react router.

**Comment by mariopeixoto** [comment]
@justin808 Hmm.. I think you might get into trouble using turbolinks unless you make sure to reapply the render script when you switch the pages... It's worth trying, at least...
