### ISSUE TITLE
Router + Fluxxor

### ISSUE THREAD

**Issue by postbud** [mariopeixoto/react-router-rails#14]
Run router in js with flux params
`var flux = new Fluxxor.Flux(...);`
`Router.run(routes, function(Handler) {  React.render( <Handler flux={flux} />, document.getElementById("app") );});`

Question:
How pass **_flux**_ in view helper?
Thanks in advance

**Comment by mariopeixoto** [comment]
For now, it's not possible. But I'm working on custom rendering to enable both client and server side rendering using custom code.

**Comment by postbud** [comment]
Clear. Thanks for the quick response
