### ISSUE TITLE
Uncaught ReferenceError: <Component> is not defined

### ISSUE THREAD

**Issue by johnernaut** [mariopeixoto/react-router-rails#17]
If I try to pass a component in via a route, such as the `AnotherPage` component you have set up in the [sample project](https://github.com/mariopeixoto/react-router-rails/blob/master/examples/react-router-example/app/assets/javascripts/components), I get the error above.

The above error goes away if I do a `//= require_tree ./` inside of the actual routes file, though: https://github.com/mariopeixoto/react-router-rails/blob/master/examples/react-router-example/app/assets/javascripts/components/routes.js.jsx

It seems that the router doesn't have access to the component definition because of how the asset pipeline orders things?  Is there a better way to fix this?

**Comment by mariopeixoto** [comment]
Hi,

The asset pipeline is a mess when it comes to import orders... The '//=require_tree ./components' imports all the files of the folder sequentially. So if your file comes after the routes.js.jsx, it won't be available yet.

The best solution I could find for that, is to move your routes file out of the components folder and import it separately after the components require. By doing that, all the components will be imported before the routes file.

Check this commit: https://github.com/mariopeixoto/react-router-rails/commit/dffb5632acd2a39e8ccaeef97f581aaa699f7f69

**Comment by johnernaut** [comment]
@mariopeixoto Yeah, I suppose that's the best option.  Thanks.
