### ISSUE TITLE
customize links

### ISSUE THREAD

**Issue by olegsobchuk** [mariopeixoto/react-router-rails#18]
Hi, there!
Can you tell me how I can add classes or ids to my React-links?
I mean, can I add class to `<Route handler={AnotherPage} path='page1'/>` for example?

**Comment by mariopeixoto** [comment]
The <Route> tag is not a link. It's simply a way to describe your routes in a react fashion.
If you want to add links you will use the <Link> tag (refer to https://github.com/rackt/react-router/blob/master/docs/guides/basics/IndexRoutes.md).

In that case you can simply add a className attribute for the Link tag: <Link to='...' className='myCssClass'>My Link</Link>
