### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by benbonnet** [mariopeixoto/react-router-rails#2]
Is the server-side rendering actually working with your tool ?
I'm expecting so far to still have `react_component('HelloMessage', {name: 'John'}, {prerender: true})` provided by react-rails

I've so far set things correctly, but from your readme, I might not get everything
I obviously dont know how to "require" the router when prerendering

Thanks for your hints (:

**Comment by i8ramin** [comment]
+1 ... I am guessing server side rendering doesn't currently work with this gem.

**Comment by mariopeixoto** [comment]
@bbnnt and @i8ramin Sorry for the delay, somehow I wasn't getting notification emails from this repo.

Please take a look at the new version of the gem - 0.13.3.

Use the react_router helper like this and you will get your component pre-rendered on the server.
<%= react_router 'MyRoutes', 'HistoryLocation', {}, { prerender_location: path_to_route } %>

I'm closing it.
