### ISSUE TITLE
Please use ReactDom.render when server rendering

### ISSUE THREAD

**Issue by yoonsy** [mariopeixoto/react-router-rails#20]
When react-rails version is 1.4.1, warning message shows up in chrome developer console like below.

> React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.

I guess react-router-rails use `React.render` method.

Could you update for react-rails ver 1.4.1?

**Comment by anthony-castrati** [comment]
I put in a pull request to use ReactDOM which resolved this issue for me. Did not realize there was already one in progress.

**Comment by borisrorsvort** [comment]
:+1:  @mariopeixoto

**Comment by yoonsy** [comment]
:+1:
