### ISSUE TITLE
Update to React-Router 1.0

### ISSUE THREAD

**Issue by mariopeixoto** [mariopeixoto/react-router-rails#23]
React Router has launched the 1.0 version.

**Comment by borisrorsvort** [comment]
Great! Any eta on this one?

**Comment by mariopeixoto** [comment]
Not yet, but I'll try look into it next week. I'm moving out so it's a mess right now, but I'll try.

**Comment by borisrorsvort** [comment]
Eheh no prob! Thanks for the great work :smile:

**Comment by yoonsy** [comment]
:+1:

**Comment by elon-kogan** [comment]
Hi. What about new release of react-router?
It wil be 2.0.0 soon. I'm so happy to have this gem. And I'm looking forward to new release of this gem.

**Comment by jodyheavener** [comment]
Any updates?

**Comment by vijaychouhan-rails** [comment]
This gem is using too old library of react-router, is there any new for new version that similar to react-router-2

**Comment by mariopeixoto** [comment]
I'm sorry, I've been pretty busy... I got no time to work on this right now, but a pull request would be very welcome.

**Comment by borisrorsvort** [comment]
@mariopeixoto maybe it would be a good idea to say in the readme that the gem is not maintained anymore. Or that it's only rails 4 compatible.

**Comment by mariopeixoto** [comment]
@borisrorsvort Done.
