### ISSUE TITLE
Asset Precompilation for Production ENV

### ISSUE THREAD

**Issue by kengreeff** [mariopeixoto/react-router-rails#24]
When deploying to production rake is aborting. Do you have any ideas as to why this is happening?

```
RAILS_ENV=production rake assets:precompile --trace
```

```
rake aborted!
NoMethodError: undefined method `resolve' for nil:NilClass
/Users/kgreeff/.rvm/gems/ruby-2.2.2/gems/react-router-rails-0.13.3.2/lib/react/router/rails/railtie.rb:11:in `block in <class:Railtie>'
```

**Comment by kengreeff** [comment]
Could maybe be linked to this:

https://github.com/rails/sprockets-rails/issues/237

**Comment by gmahajan31** [comment]
I am also running into this error. Any solution yet?

**Comment by kengreeff** [comment]
I just set my gem file to use the older version of sprockets:

gem 'sprockets', '3.2'

Working in the meantime.

**Comment by dyakubovich** [comment]
This solution is not help me. Any solution yet?

**Comment by dyakubovich** [comment]
I  set my gem file to use this version of sprockets:

gem 'sprockets', '2.9'

It working for me.

**Comment by yoonsy** [comment]
https://github.com/reactjs/react-rails/commit/e1e319d3d0258c66776141857ccbf8b3519105b5

**Comment by cimm** [comment]
Trying to update Rails to fix an XSS vulnerability but failing to deploy as `react-router-rails` is not compatible with the latests `react-rails`: version `1.8.2`. Any plans to update this gem so I can run with the latest and greatest? I still get the same error when pointing my Gemfile to 3681fbb.

**Comment by phthhieu** [comment]
follow up @kubaaa answer:
- add `gem 'sprockets', '2.9'` to your gemfile
- run `bundle update`
- deploy again!

**Comment by cimm** [comment]
@phthhieu Thanks but downgrading Sprockets is not an option, other gems depend on a `> 3` Sprockets version. Any idea how to fix `react-router-rails` so it works with newer Sprockets version?

**Comment by rubydog** [comment]
Anybody got this working? I'm using Rails 5.

**Comment by jacklin10** [comment]
I'm having this same issue.  Downgrading sprockets didn't work for me either.  
Looks like the last release for this gem was 2015.  Is it still being maintained?
