### ISSUE TITLE
Example code not enough to get running

### ISSUE THREAD

**Issue by jcgertig** [mariopeixoto/react-router-rails#3]
I was unable with the given examples to get this to work with a fresh rails app
https://www.dropbox.com/s/j1btljuh3tm0vnu/Screenshot%202015-05-21%2013.48.15.png?dl=0

my routes.jsx

```
var Route = ReactRouter.Route;
var DefaultRoute = ReactRouter.DefaultRoute;

window.MyRoutes = (
  <Route path="/" handler={App}>
    <DefaultRoute name='home' handler={Home} />
  </Route>
);
```

I am using 

```
<%= react_router 'MyRoutes', 'HistoryLocation' %>
```

in my application.html

Definitely seams like some sort of route needs to be  done in the rails routes file.

**Comment by jcgertig** [comment]
Adding 

```
get '*any', to: 'application#index'
root 'application#index'
```

to the `routes` file and

```
rescue_from ActionView::MissingTemplate do render '/generic_page' end
def index
end
```

to the `application_controller.rb`
works

**Comment by mariopeixoto** [comment]
@jcgertig Sorry for the delay, I wasn't getting notification emails from this repo.

Happy to know that you got it working.
