### ISSUE TITLE
Cannot require react-router-rails in plugin engine

### ISSUE THREAD

**Issue by ghost** [mariopeixoto/react-router-rails#32]
I'm writing a little CMS plugin and I decided to use React.js for frontend. Thus I added `react-rails` and `react-router-rails` to my `.gemspec` file. Here it is:

```
    s.add_dependency "react-rails"
    s.add_dependency "react-router-rails"
```

And then in my `engine.rb`:

```
    require 'react-rails'
    require 'react-router-rails'
```

But when I try to do anything -- for example, create a model, it returns me the following error:

```
    /home/alex/Desktop/WORKSPACE/rails/multiflora/lib/multiflora/engine.rb:5:in `require': cannot load such file -- react_router_rails (LoadError)
```

Have I done something wrong or this gem isn't supposed to be used in plugins?

**Comment by mariopeixoto** [comment]
This gem is not maintained anymore. Sorry about that.
