### ISSUE TITLE
Example does not work on Rails 5 and updated react-rails

### ISSUE THREAD

**Issue by caramori** [mariopeixoto/react-router-rails#33]
Made a test on Rails 5 and react-rails and apparently the example does not work. 

Output was:

784: unexpected token at 'Warning: You are manually calling a React.PropTypes validation function for the `name` prop on `UnknownComponent`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `path` prop on `UnknownComponent`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `handler` prop on `UnknownComponent`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
Warning: You are manually calling a React.PropTypes validation function for the `ignoreScrollBehavior` prop on `UnknownComponent`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
["err","TypeError: Object #<Object> has no method 'renderToString'","TypeError: Object #<Object> has no method 'renderToString'\n    at Function.eval (eval at <anonymous> (/tmp/execjs20161218-26269-1p4p13gjs:24944:8), <anonymous>:4:27)\n    at Function.dispatchHandler (/tmp/execjs20161218-26269-1p4p13gjs:23382:23)\n    at /tmp/execjs20161218-26269-1p4p13gjs:23350:30\n    at /tmp/execjs20161218-26269-1p4p13gjs:24015:10\n    at /tmp/execjs20161218-26269-1p4p13gjs:24015:10\n    at Function.Transition.to (/tmp/execjs20161218-26269-1p4p13gjs:24018:16)\n    at /tmp/execjs20161218-26269-1p4p13gjs:23349:23\n    at Function.Transition.from (/tmp/execjs20161218-26269-1p4p13gjs:23997:16)\n    at Function.dispatch (/tmp/execjs20161218-26269-1p4p13gjs:23346:21)\n    at Function.refresh (/tmp/execjs20161218-26269-1p4p13gjs:23397:17)"]'
Extracted source (around line #1):
1
              
<%= react_router 'MyRoutes', 'HistoryLocation', { foo: 'Foo' }, { prerender_location: @location_path } %>

**Comment by mariopeixoto** [comment]
This gem is only supported in Rails 4 and it's not maintained anymore. Sorry about that.
