### ISSUE TITLE
Issues getting started

### ISSUE THREAD

**Issue by tgoldenberg** [mariopeixoto/react-router-rails#5]
Hi, first of all, thank you for this gem! I am unable to get started with the code provided. My MyRoutes.jsx  is in this gist : 

https://gist.github.com/tgoldenberg/e18a6387576e431585d0

If I use the plain 'routes' variable in the example, I get an error because it isn't defined. Can you provide some starting instructions that are more explicit and clear? 
Thank you.

**Comment by mariopeixoto** [comment]
@tgoldenberg Could you send me the error message you're getting?

**Comment by tgoldenberg** [comment]
Here is the full error message: 

Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.invariant @ react.self-93bc62cb6c7b74ee7e5a2fcf623f3abbd365440bf90eba740c625f159078aa82.js?body=1:18473ReactMount._registerComponent @ react.self-93bc62cb6c7b74ee7e5a2fcf623f3abbd365440bf90eba740c625f159078aa82.js?body=1:12146ReactMount._renderNewRootComponent @ react.self-93bc62cb6c7b74ee7e5a2fcf623f3abbd365440bf90eba740c625f159078aa82.js?body=1:12186ReactPerf.measure.wrapper @ react.self-93bc62cb6c7b74ee7e5a2fcf623f3abbd365440bf90eba740c625f159078aa82.js?body=1:13428ReactMount.render @ react.self-93bc62cb6c7b74ee7e5a2fcf623f3abbd365440bf90eba740c625f159078aa82.js?body=1:12284ReactPerf.measure.wrapper @ react.self-93bc62cb6c7b74ee7e5a2fcf623f3abbd365440bf90eba740c625f159078aa82.js?body=1:13428(anonymous function) @ App.self-f95c4e6e9bb5a69624ff4cea0e7bdc2b3f0e38abc36205fc8e5ab8af066a6c8e.js?body=1:13React.createClass.statics.run.dispatchHandler @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:1905(anonymous function) @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:1873(anonymous function) @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:2538Transition.to @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:2541(anonymous function) @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:1872Transition.from @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:2520dispatch @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:1869refresh @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:1920run @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:1916runRouter @ react_router.self-a3943585cbcc7a7882eca04c71f0b40439960cdb60833a1e4af8d3be28cf5b47.js?body=1:2088(anonymous function) @ App.self-f95c4e6e9bb5a69624ff4cea0e7bdc2b3f0e38abc36205fc8e5ab8af066a6c8e.js?body=1:12

**Comment by tgoldenberg** [comment]
Mario, I'm sure this sounds really stupid, but you should specify that there are examples in the repo. I didn't realize this until just now and it solved all of my problems. I was having a hard time figuring out how to configure everything but with the example it all makes sense. Thank you for this gem :+1:

**Comment by mariopeixoto** [comment]
@tgoldenberg It's not stupid at all. Actually I only added the example days ago, I'm still working on proper docs.

Thanks for the feedback.
