### ISSUE TITLE
really want to use this

### ISSUE THREAD

**Issue by dmlond** [mariopeixoto/react-router-rails#6]
but at this point the prerender_location feature is too sparsely documented.  I played around with it for a day, but I could never get it to fully route.  I created:

app/assets/javascripts/components/routes.js.jsx

```
var Route = ReactRouter.Route;
this.DDSRoutes = (
  <Route handler={App} path='/'>
    <Route name='splash' handler={Splash} path='splash' />
  </Route>
);
```

app/assets/javascripts/components/app.js.jsx

```
var App = React.createClass({
  render: function() {
    return (
      <div>
        <h1>App {this.props.foo}</h1>
        <ReactRouter.RouteHandler/>
      </div>
    )
  }
});
```

app/assets/javascripts/components/splash.js.jsx

```
var Splash = React.createClass({
  render: function() {
    return (
      <div>
        <h1>Splash Page</h1>
      </div>
    )
  }
});
```

app/controllers/front_end_controller.rb

```
class FrontEndController < ApplicationController
  def index
  end
end
```

app/views/front_end/index.html

```
<%= react_router 'DDSRoutes', 'HistoryLocation', {foo: 'this is foo prop'}, { prerender_location: '/' } %>
```

```
Rails.application.routes.draw do
  root 'front_end#index'
  get "/*path" => "front_end#index"
end
```

I can get the base App to mount at '/', but then I get many Undefined errors:
routes.self: Undefined Object 'ReactRouter' at the first line, e.g. var Route = ReactRouter.Route;

and I can never get it present Splash at '/splash'

I am using the latest version released june 20 (0.13.3)  I get that this is bleeding edge, and I really hope it stabilizes.  If I am doing something wrong, let me know.

**Comment by mariopeixoto** [comment]
Hi @dmlond,

Sorry for the poor documentation on that feature. I'll try to improve it.
In the meantime, please take a look at the example project I've added to the repo (https://github.com/mariopeixoto/react-router-rails/tree/master/examples/react-router-example).

If you publish your project on github or send to me I can help pointing out what's wrong.

**Comment by dmlond** [comment]
I was able to get your example working with ruby 2.2.2p95 and node v0.10.36 as the javascript runtime.  I then started to make changes in your Gemfile to match versions of gems that I am using in my project.  When I upgrade to rails 4.2.1, things stop working.  I will keep looking into it to see what version of rails I can get to before things stop working.

**Comment by dmlond** [comment]
it stops working with rails 4.2.0 as well.

**Comment by mariopeixoto** [comment]
@dmlond Could you send me your Gemfile? I have the project updated to rails 4.2.1 and ruby 2.2.2p95 and still works on my end.

**Comment by dmlond** [comment]
ok. I figured out what was happening.  It works with rails 4.2.1.  I was running it in a docker container, and , evidently, the default rails s does not attach the server to 0.0.0.0.  I added thin to my Gemfile, and ran thin start instead, which defaults to 0.0.0.0, and your code works.  You can close the issue, but please continue to document things.

**Comment by dmlond** [comment]
can you make the example pass initial properties into the application using the react_router view helper.  I am pretty sure this worked in the previous version like:

<%= react_router 'MyRoutes', 'HistoryLocation', {'foo' => 'foo'}, { prerender_location: @location_path } %>

so that I can do:

/** @jsx React.DOM */

var RouteHandler = ReactRouter.RouteHandler,
    Link = ReactRouter.Link;

var App = React.createClass({
  render: function() {
    return (
      <div>
        <nav>
          <ul>
            <li>
              <Link to='/'>Hello World</Link>
            </li>
            <li>
              <Link to='/page1'>Another Page</Link>
            </li>
          </ul>
        </nav>
        <p>foo: {this.props.foo}</p>
        <RouteHandler />
      </div>
    );
  }
});
