### ISSUE TITLE
pass properties using the react_router view helper

### ISSUE THREAD

**Issue by dmlond** [mariopeixoto/react-router-rails#7]
Can you make an example that passes initial properties to the rendered route.  I am pretty sure this worked in a previous version of this code like:

<%= react_router 'MyRoutes', 'HistoryLocation', {'foo' => 'foo'}, { prerender_location: @location_path } %>

which would allow me to do the following in app/assets/javascript/components/app.js.jsx

```
/** @jsx React.DOM */

var RouteHandler = ReactRouter.RouteHandler,
    Link = ReactRouter.Link;

var App = React.createClass({
  render: function() {
    return (
      <div>
        <nav>
          <ul>
            <li>
              <Link to='/'>Hello World</Link>
            </li>
            <li>
              <Link to='/page1'>Another Page</Link>
            </li>
          </ul>
        </nav>
        <p>foo: {this.props.foo}</p>
        <RouteHandler />
      </div>
    );
  }
});
```

**Comment by mariopeixoto** [comment]
Hi, it turns out that the UJS javascript was replacing the generated markup because it wasn't considering the data provided.

I'll be releasing a new version soon, but for now please put this in your Gemfile.

```
  gem 'react-router-rails', :git => 'git@github.com:mariopeixoto/react-router-rails.git', :branch => 'v0.13.3p1'
```

**Comment by dmlond** [comment]
thanks. I will give this a try.

**Comment by dmlond** [comment]
that works.  Thanks. I will watch for you to release a new official version :)
